CREATE OR REPLACE PACKAGE calculator_pkg AS
  FUNCTION add(a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION subtract(a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION multiply(a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION divide(a NUMBER, b NUMBER) RETURN NUMBER;
END calculator_pkg;
/
