CREATE OR REPLACE PACKAGE CALCULATOR_PKG AS
  DIVISION_BY_ZERO EXCEPTION;
  PRAGMA EXCEPTION_INIT ( DIVISION_BY_ZERO,-20001 );
  FUNCTION ADD (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER;
  FUNCTION SUBTRACT (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER;
  FUNCTION MULTIPLY (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER;
  FUNCTION DIVIDE (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER;
END CALCULATOR_PKG;
/

CREATE OR REPLACE PACKAGE BODY CALCULATOR_PKG AS

  FUNCTION ADD (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER IS
  BEGIN
    RETURN A + B;
  END ADD;

  FUNCTION SUBTRACT (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER IS
  BEGIN
    RETURN A - B;
  END SUBTRACT;

  FUNCTION MULTIPLY (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER IS
  BEGIN
    RETURN A * B;
  END MULTIPLY;

  FUNCTION DIVIDE (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF B = 0 THEN
      RAISE DIVISION_BY_ZERO;
    END IF;
    RETURN A / B;
  END DIVIDE;

END CALCULATOR_PKG;
/