CREATE OR REPLACE PACKAGE CALCULATOR_PKG AS
  DIVISION_BY_ZERO EXCEPTION;
  PRAGMA EXCEPTION_INIT ( DIVISION_BY_ZERO,-20004 );
  NEGATIVE_ROOT_FOR_EVEN_DEGREE EXCEPTION;
  PRAGMA EXCEPTION_INIT ( NEGATIVE_ROOT_FOR_EVEN_DEGREE, -20005 );

  FUNCTION ADD (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER;
  FUNCTION SUBTRACT (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER;
  FUNCTION MULTIPLY (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER;
  FUNCTION DIVIDE (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER;
  FUNCTION NTH_POWER (
    A NUMBER
   ,N NUMBER
  ) RETURN NUMBER;
  FUNCTION NTH_ROOT (
    A NUMBER
   ,N NUMBER
  ) RETURN NUMBER;
END CALCULATOR_PKG;
/

CREATE OR REPLACE PACKAGE BODY CALCULATOR_PKG AS

  FUNCTION ADD (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER IS
  BEGIN
    RETURN A + B;
  END ADD;

  FUNCTION SUBTRACT (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER IS
  BEGIN
    RETURN A - B;
  END SUBTRACT;

  FUNCTION MULTIPLY (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER IS
  BEGIN
    RETURN A * B;
  END MULTIPLY;

  FUNCTION DIVIDE (
    A NUMBER
   ,B NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF B = 0 THEN
      RAISE DIVISION_BY_ZERO;
    END IF;
    RETURN A / B;
  END DIVIDE;

  FUNCTION NTH_POWER (
    A NUMBER
   ,N NUMBER
  ) RETURN NUMBER IS
  BEGIN
    RETURN POWER(A, N);
  END NTH_POWER;

  FUNCTION NTH_ROOT (
    A NUMBER
   ,N NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF MOD(N, 2) = 0 AND A < 0 THEN
      RAISE NEGATIVE_ROOT_FOR_EVEN_DEGREE;
    END IF;
    RETURN POWER(A, 1/N);
  END NTH_ROOT;

END CALCULATOR_PKG;
/