CREATE OR REPLACE PACKAGE DISTANCE_CONVERTER_PKG AS
  DISTANCE_NEGATIVE EXCEPTION;
  FUNCTION METERS_TO_YARDS (
    P_METERS NUMBER
  ) RETURN NUMBER;
  FUNCTION YARDS_TO_METERS (
    P_YARDS NUMBER
  ) RETURN NUMBER;
  FUNCTION METERS_TO_FEET (
    P_METERS NUMBER
  ) RETURN NUMBER;
  FUNCTION FEET_TO_METERS (
    P_FEET NUMBER
  ) RETURN NUMBER;
  FUNCTION METERS_TO_INCHES (
    P_METERS NUMBER
  ) RETURN NUMBER;
  FUNCTION INCHES_TO_METERS (
    P_INCHES NUMBER
  ) RETURN NUMBER;
  FUNCTION KILOMETERS_TO_MILES (
    P_KILOMETERS NUMBER
  ) RETURN NUMBER;
  FUNCTION MILES_TO_KILOMETERS (
    P_MILES NUMBER
  ) RETURN NUMBER;
END DISTANCE_CONVERTER_PKG;
/

CREATE OR REPLACE PACKAGE BODY DISTANCE_CONVERTER_PKG AS

  FUNCTION METERS_TO_YARDS (
    P_METERS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_METERS < 0 THEN
      RAISE DISTANCE_NEGATIVE;
    END IF;
    RETURN P_METERS * 1.0936133;
  END METERS_TO_YARDS;

  FUNCTION YARDS_TO_METERS (
    P_YARDS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_YARDS < 0 THEN
      RAISE DISTANCE_NEGATIVE;
    END IF;
    RETURN P_YARDS / 1.0936133;
  END YARDS_TO_METERS;

  FUNCTION METERS_TO_FEET (
    P_METERS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_METERS < 0 THEN
      RAISE DISTANCE_NEGATIVE;
    END IF;
    RETURN P_METERS * 3.2808399;
  END METERS_TO_FEET;

  FUNCTION FEET_TO_METERS (
    P_FEET NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_FEET < 0 THEN
      RAISE DISTANCE_NEGATIVE;
    END IF;
    RETURN P_FEET / 3.2808399;
  END FEET_TO_METERS;

  FUNCTION METERS_TO_INCHES (
    P_METERS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_METERS < 0 THEN
      RAISE DISTANCE_NEGATIVE;
    END IF;
    RETURN P_METERS * 39.3700787;
  END METERS_TO_INCHES;

  FUNCTION INCHES_TO_METERS (
    P_INCHES NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_INCHES < 0 THEN
      RAISE DISTANCE_NEGATIVE;
    END IF;
    RETURN P_INCHES / 39.3700787;
  END INCHES_TO_METERS;

  FUNCTION KILOMETERS_TO_MILES (
    P_KILOMETERS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_KILOMETERS < 0 THEN
      RAISE DISTANCE_NEGATIVE;
    END IF;
    RETURN P_KILOMETERS * 0.621371192;
  END KILOMETERS_TO_MILES;

  FUNCTION MILES_TO_KILOMETERS (
    P_MILES NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_MILES < 0 THEN
      RAISE DISTANCE_NEGATIVE;
    END IF;
    RETURN P_MILES / 0.621371192;
  END MILES_TO_KILOMETERS;
END DISTANCE_CONVERTER_PKG;
/