CREATE OR REPLACE PACKAGE TEMPERATURE_CONVERTER_PKG AS
  ABSOLUTE_ZERO EXCEPTION;
  PRAGMA EXCEPTION_INIT ( ABSOLUTE_ZERO,-20002 );
  FUNCTION CELSIUS_TO_KELVIN (
    P_CELSIUS NUMBER
  ) RETURN NUMBER;
  FUNCTION KELVIN_TO_CELSIUS (
    P_KELVIN NUMBER
  ) RETURN NUMBER;
  FUNCTION CELSIUS_TO_FAHRENHEIT (
    P_CELSIUS NUMBER
  ) RETURN NUMBER;
  FUNCTION FAHRENHEIT_TO_CELSIUS (
    P_FAHRENHEIT NUMBER
  ) RETURN NUMBER;
  FUNCTION KELVIN_TO_FAHRENHEIT (
    P_KELVIN NUMBER
  ) RETURN NUMBER;
  FUNCTION FAHRENHEIT_TO_KELVIN (
    P_FAHRENHEIT NUMBER
  ) RETURN NUMBER;
END TEMPERATURE_CONVERTER_PKG;
/

CREATE OR REPLACE PACKAGE BODY TEMPERATURE_CONVERTER_PKG AS

  FUNCTION CELSIUS_TO_KELVIN (
    P_CELSIUS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_CELSIUS < -273.15 THEN
      RAISE ABSOLUTE_ZERO;
    END IF;
    RETURN P_CELSIUS + 273.15;
  END CELSIUS_TO_KELVIN;

  FUNCTION KELVIN_TO_CELSIUS (
    P_KELVIN NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_KELVIN < 0 THEN
      RAISE ABSOLUTE_ZERO;
    END IF;
    RETURN P_KELVIN - 273.15;
  END KELVIN_TO_CELSIUS;

  FUNCTION CELSIUS_TO_FAHRENHEIT (
    P_CELSIUS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_CELSIUS < -273.15 THEN
      RAISE ABSOLUTE_ZERO;
    END IF;
    RETURN P_CELSIUS * 9 / 5 + 32;
  END CELSIUS_TO_FAHRENHEIT;

  FUNCTION FAHRENHEIT_TO_CELSIUS (
    P_FAHRENHEIT NUMBER
  ) RETURN NUMBER IS
    L_CELSIUS NUMBER;
  BEGIN
    L_CELSIUS := ( P_FAHRENHEIT - 32 ) * 5 / 9;
    IF L_CELSIUS < -273.15 THEN
      RAISE ABSOLUTE_ZERO;
    END IF;
    RETURN L_CELSIUS;
  END FAHRENHEIT_TO_CELSIUS;

  FUNCTION KELVIN_TO_FAHRENHEIT (
    P_KELVIN NUMBER
  ) RETURN NUMBER IS
    L_CELSIUS NUMBER;
  BEGIN
    IF P_KELVIN < 0 THEN
      RAISE ABSOLUTE_ZERO;
    END IF;
    L_CELSIUS := P_KELVIN - 273.15;
    RETURN L_CELSIUS * 9 / 5 + 32;
  END KELVIN_TO_FAHRENHEIT;

  FUNCTION FAHRENHEIT_TO_KELVIN (
    P_FAHRENHEIT NUMBER
  ) RETURN NUMBER IS
    L_CELSIUS NUMBER;
  BEGIN
    L_CELSIUS := ( P_FAHRENHEIT - 32 ) * 5 / 9;
    IF L_CELSIUS < -273.15 THEN
      RAISE ABSOLUTE_ZERO;
    END IF;
    RETURN L_CELSIUS + 273.15;
  END FAHRENHEIT_TO_KELVIN;
END TEMPERATURE_CONVERTER_PKG;
/