CREATE OR REPLACE PACKAGE VOLUME_CONVERTER_PKG AS
  VOLUME_NEGATIVE EXCEPTION;
  PRAGMA EXCEPTION_INIT ( VOLUME_NEGATIVE,-20003 );
  FUNCTION LITERS_TO_GALLONS (
    P_LITERS NUMBER
  ) RETURN NUMBER;
  FUNCTION GALLONS_TO_LITERS (
    P_GALLONS NUMBER
  ) RETURN NUMBER;
  FUNCTION LITERS_TO_PINTS (
    P_LITERS NUMBER
  ) RETURN NUMBER;
  FUNCTION PINTS_TO_LITERS (
    P_PINTS NUMBER
  ) RETURN NUMBER;
  FUNCTION LITERS_TO_FLUID_OUNCES (
    P_LITERS NUMBER
  ) RETURN NUMBER;
  FUNCTION FLUID_OUNCES_TO_LITERS (
    P_FLUID_OUNCES NUMBER
  ) RETURN NUMBER;
  FUNCTION CUBIC_METERS_TO_CUBIC_FEET (
    P_CUBIC_METERS NUMBER
  ) RETURN NUMBER;
  FUNCTION CUBIC_FEET_TO_CUBIC_METERS (
    P_CUBIC_FEET NUMBER
  ) RETURN NUMBER;
END VOLUME_CONVERTER_PKG;
/

CREATE OR REPLACE PACKAGE BODY VOLUME_CONVERTER_PKG AS

  FUNCTION LITERS_TO_GALLONS (
    P_LITERS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_LITERS < 0 THEN
      RAISE VOLUME_NEGATIVE;
    END IF;
    RETURN P_LITERS * 0.264172052;
  END LITERS_TO_GALLONS;

  FUNCTION GALLONS_TO_LITERS (
    P_GALLONS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_GALLONS < 0 THEN
      RAISE VOLUME_NEGATIVE;
    END IF;
    RETURN P_GALLONS / 0.264172052;
  END GALLONS_TO_LITERS;

  FUNCTION LITERS_TO_PINTS (
    P_LITERS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_LITERS < 0 THEN
      RAISE VOLUME_NEGATIVE;
    END IF;
    RETURN P_LITERS * 2.11337642;
  END LITERS_TO_PINTS;

  FUNCTION PINTS_TO_LITERS (
    P_PINTS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_PINTS < 0 THEN
      RAISE VOLUME_NEGATIVE;
    END IF;
    RETURN P_PINTS / 2.11337642;
  END PINTS_TO_LITERS;

  FUNCTION LITERS_TO_FLUID_OUNCES (
    P_LITERS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_LITERS < 0 THEN
      RAISE VOLUME_NEGATIVE;
    END IF;
    RETURN P_LITERS * 33.8140227;
  END LITERS_TO_FLUID_OUNCES;

  FUNCTION FLUID_OUNCES_TO_LITERS (
    P_FLUID_OUNCES NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_FLUID_OUNCES < 0 THEN
      RAISE VOLUME_NEGATIVE;
    END IF;
    RETURN P_FLUID_OUNCES / 33.8140227;
  END FLUID_OUNCES_TO_LITERS;

  FUNCTION CUBIC_METERS_TO_CUBIC_FEET (
    P_CUBIC_METERS NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_CUBIC_METERS < 0 THEN
      RAISE VOLUME_NEGATIVE;
    END IF;
    RETURN P_CUBIC_METERS * 35.3146667;
  END CUBIC_METERS_TO_CUBIC_FEET;

  FUNCTION CUBIC_FEET_TO_CUBIC_METERS (
    P_CUBIC_FEET NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_CUBIC_FEET < 0 THEN
      RAISE VOLUME_NEGATIVE;
    END IF;
    RETURN P_CUBIC_FEET / 35.3146667;
  END CUBIC_FEET_TO_CUBIC_METERS;
END VOLUME_CONVERTER_PKG;
/