CREATE OR REPLACE PACKAGE DISTANCE_CONVERTER_PKG_TEST IS
--%suite(Distance Converter Package Tests)
--%suitepath(Distance_Converter)

  --%test(Meters to Yards conversion)
  PROCEDURE TEST_METERS_TO_YARDS;

  --%test(Meters to Yards negative distance)
  --%throws(distance_converter_pkg.distance_negative)
  PROCEDURE TEST_METERS_TO_YARDS_NEGATIVE;

  --%test(Yards to Meters conversion)
  PROCEDURE TEST_YARDS_TO_METERS;

  --%test(Yards to Meters negative distance)
  --%throws(distance_converter_pkg.distance_negative)
  PROCEDURE TEST_YARDS_TO_METERS_NEGATIVE;

  --%test(Meters to Feet conversion)
  PROCEDURE TEST_METERS_TO_FEET;

  --%test(Meters to Feet negative distance)
  --%throws(distance_converter_pkg.distance_negative)
  PROCEDURE TEST_METERS_TO_FEET_NEGATIVE;

  --%test(Feet to Meters conversion)
  PROCEDURE TEST_FEET_TO_METERS;

  --%test(Feet to Meters negative distance)
  --%throws(distance_converter_pkg.distance_negative)
  PROCEDURE TEST_FEET_TO_METERS_NEGATIVE;

  --%test(Meters to Inches conversion)
  PROCEDURE TEST_METERS_TO_INCHES;

  --%test(Meters to Inches negative distance)
  --%throws(distance_converter_pkg.distance_negative)
  PROCEDURE TEST_METERS_TO_INCHES_NEGATIVE;

  --%test(Inches to Meters conversion)
  PROCEDURE TEST_INCHES_TO_METERS;

  --%test(Inches to Meters negative distance)
  --%throws(distance_converter_pkg.distance_negative)
  PROCEDURE TEST_INCHES_TO_METERS_NEGATIVE;

  --%test(Kilometers to Miles conversion)
  PROCEDURE TEST_KILOMETERS_TO_MILES;

  --%test(Kilometers to Miles negative distance)
  --%throws(distance_converter_pkg.distance_negative)
  PROCEDURE TEST_KILOMETERS_TO_MILES_NEGATIVE;

  --%test(Miles to Kilometers conversion)
  PROCEDURE TEST_MILES_TO_KILOMETERS;

  --%test(Miles to Kilometers negative distance)
  --%throws(distance_converter_pkg.distance_negative)
  PROCEDURE TEST_MILES_TO_KILOMETERS_NEGATIVE;

END DISTANCE_CONVERTER_PKG_TEST;
/

CREATE OR REPLACE PACKAGE BODY DISTANCE_CONVERTER_PKG_TEST IS

  PROCEDURE TEST_METERS_TO_YARDS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_YARDS(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      1.0936
     ,1.0937
    );
  END TEST_METERS_TO_YARDS;

  PROCEDURE TEST_METERS_TO_YARDS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_YARDS(-1);
/*   EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001); */
  END TEST_METERS_TO_YARDS_NEGATIVE;

  PROCEDURE TEST_YARDS_TO_METERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.YARDS_TO_METERS(1.0936133);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.9999
     ,1.0001
    );
  END TEST_YARDS_TO_METERS;

  PROCEDURE TEST_YARDS_TO_METERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.YARDS_TO_METERS(-1);
/*   EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001); */
  END TEST_YARDS_TO_METERS_NEGATIVE;

  PROCEDURE TEST_METERS_TO_FEET IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_FEET(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      3.2808
     ,3.2809
    );
  END TEST_METERS_TO_FEET;

  PROCEDURE TEST_METERS_TO_FEET_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_FEET(-1);
/*   EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001); */
  END TEST_METERS_TO_FEET_NEGATIVE;

  PROCEDURE TEST_FEET_TO_METERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.FEET_TO_METERS(3.2808399);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.9999
     ,1.0001
    );
  END TEST_FEET_TO_METERS;

  PROCEDURE TEST_FEET_TO_METERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.FEET_TO_METERS(-1);
/*   EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001); */
  END TEST_FEET_TO_METERS_NEGATIVE;

  PROCEDURE TEST_METERS_TO_INCHES IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_INCHES(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      39.3700
     ,39.3701
    );
  END TEST_METERS_TO_INCHES;

  PROCEDURE TEST_METERS_TO_INCHES_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_INCHES(-1);
/*   EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001); */
  END TEST_METERS_TO_INCHES_NEGATIVE;

  PROCEDURE TEST_INCHES_TO_METERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.INCHES_TO_METERS(39.3700787);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.9999
     ,1.0001
    );
  END TEST_INCHES_TO_METERS;

  PROCEDURE TEST_INCHES_TO_METERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.INCHES_TO_METERS(-1);
/*   EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001); */
  END TEST_INCHES_TO_METERS_NEGATIVE;

  PROCEDURE TEST_KILOMETERS_TO_MILES IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.KILOMETERS_TO_MILES(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.6213
     ,0.6214
    );
  END TEST_KILOMETERS_TO_MILES;

  PROCEDURE TEST_KILOMETERS_TO_MILES_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.KILOMETERS_TO_MILES(-1);
/*   EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001); */
  END TEST_KILOMETERS_TO_MILES_NEGATIVE;

  PROCEDURE TEST_MILES_TO_KILOMETERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.MILES_TO_KILOMETERS(0.621371192);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.9999
     ,1.0001
    );
  END TEST_MILES_TO_KILOMETERS;

  PROCEDURE TEST_MILES_TO_KILOMETERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.MILES_TO_KILOMETERS(-1);
/*   EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001); */
  END TEST_MILES_TO_KILOMETERS_NEGATIVE;

END DISTANCE_CONVERTER_PKG_TEST;
/