CREATE OR REPLACE PACKAGE TEMPERATURE_CONVERTER_PKG_TEST IS
--%suite(Temperature Converter Package Tests)
--%suitepath(Temperature_Converter)

  --%test(Celsius to Kelvin conversion)
  PROCEDURE TEST_CELSIUS_TO_KELVIN;

  --%test(Celsius to Kelvin below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE TEST_CELSIUS_TO_KELVIN_NEGATIVE;

  --%test(Kelvin to Celsius conversion)
  PROCEDURE TEST_KELVIN_TO_CELSIUS;

  --%test(Kelvin to Celsius below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE TEST_KELVIN_TO_CELSIUS_NEGATIVE;

  --%test(Celsius to Fahrenheit conversion)
  PROCEDURE TEST_CELSIUS_TO_FAHRENHEIT;

  --%test(Celsius to Fahrenheit below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE TEST_CELSIUS_TO_FAHRENHEIT_NEGATIVE;

  --%test(Fahrenheit to Celsius conversion)
  PROCEDURE TEST_FAHRENHEIT_TO_CELSIUS;

  --%test(Fahrenheit to Celsius below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE TEST_FAHRENHEIT_TO_CELSIUS_NEGATIVE;

  --%test(Kelvin to Fahrenheit conversion)
  PROCEDURE TEST_KELVIN_TO_FAHRENHEIT;

  --%test(Kelvin to Fahrenheit below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE TEST_KELVIN_TO_FAHRENHEIT_NEGATIVE;

  --%test(Fahrenheit to Kelvin conversion)
  PROCEDURE TEST_FAHRENHEIT_TO_KELVIN;

  --%test(Fahrenheit to Kelvin below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE TEST_FAHRENHEIT_TO_KELVIN_NEGATIVE;

END TEMPERATURE_CONVERTER_PKG_TEST;
/

CREATE OR REPLACE PACKAGE BODY TEMPERATURE_CONVERTER_PKG_TEST IS

  PROCEDURE TEST_CELSIUS_TO_KELVIN IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.CELSIUS_TO_KELVIN(0);
    UT.EXPECT(L_RESULT).TO_EQUAL(273.15);
  END TEST_CELSIUS_TO_KELVIN;

  PROCEDURE TEST_CELSIUS_TO_KELVIN_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.CELSIUS_TO_KELVIN(-274);
/*   EXCEPTION
    WHEN temperature_converter_pkg.absolute_zero THEN
      ut.expect(sqlcode).to_equal(-20002); */
  END TEST_CELSIUS_TO_KELVIN_NEGATIVE;

  PROCEDURE TEST_KELVIN_TO_CELSIUS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.KELVIN_TO_CELSIUS(273.15);
    UT.EXPECT(L_RESULT).TO_EQUAL(0);
  END TEST_KELVIN_TO_CELSIUS;

  PROCEDURE TEST_KELVIN_TO_CELSIUS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.KELVIN_TO_CELSIUS(-1);
/*   EXCEPTION
    WHEN temperature_converter_pkg.absolute_zero THEN
      ut.expect(sqlcode).to_equal(-20002); */
  END TEST_KELVIN_TO_CELSIUS_NEGATIVE;

  PROCEDURE TEST_CELSIUS_TO_FAHRENHEIT IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.CELSIUS_TO_FAHRENHEIT(0);
    UT.EXPECT(L_RESULT).TO_EQUAL(32);
  END TEST_CELSIUS_TO_FAHRENHEIT;

  PROCEDURE TEST_CELSIUS_TO_FAHRENHEIT_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.CELSIUS_TO_FAHRENHEIT(-274);
/*   EXCEPTION
    WHEN temperature_converter_pkg.absolute_zero THEN
      ut.expect(sqlcode).to_equal(-20002); */
  END TEST_CELSIUS_TO_FAHRENHEIT_NEGATIVE;

  PROCEDURE TEST_FAHRENHEIT_TO_CELSIUS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.FAHRENHEIT_TO_CELSIUS(32);
    UT.EXPECT(L_RESULT).TO_EQUAL(0);
  END TEST_FAHRENHEIT_TO_CELSIUS;

  PROCEDURE TEST_FAHRENHEIT_TO_CELSIUS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.FAHRENHEIT_TO_CELSIUS(-500);
/*   EXCEPTION
    WHEN temperature_converter_pkg.absolute_zero THEN
      ut.expect(sqlcode).to_equal(-20002); */
  END TEST_FAHRENHEIT_TO_CELSIUS_NEGATIVE;

  PROCEDURE TEST_KELVIN_TO_FAHRENHEIT IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.KELVIN_TO_FAHRENHEIT(273.15);
    UT.EXPECT(L_RESULT).TO_EQUAL(32);
  END TEST_KELVIN_TO_FAHRENHEIT;

  PROCEDURE TEST_KELVIN_TO_FAHRENHEIT_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.KELVIN_TO_FAHRENHEIT(-1);
/*   EXCEPTION
    WHEN temperature_converter_pkg.absolute_zero THEN
      ut.expect(sqlcode).to_equal(-20002); */
  END TEST_KELVIN_TO_FAHRENHEIT_NEGATIVE;

  PROCEDURE TEST_FAHRENHEIT_TO_KELVIN IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.FAHRENHEIT_TO_KELVIN(32);
    UT.EXPECT(L_RESULT).TO_EQUAL(273.15);
  END TEST_FAHRENHEIT_TO_KELVIN;

  PROCEDURE TEST_FAHRENHEIT_TO_KELVIN_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := TEMPERATURE_CONVERTER_PKG.FAHRENHEIT_TO_KELVIN(-500);
/*   EXCEPTION
    WHEN temperature_converter_pkg.absolute_zero THEN
      ut.expect(sqlcode).to_equal(-20002); */
  END TEST_FAHRENHEIT_TO_KELVIN_NEGATIVE;

END TEMPERATURE_CONVERTER_PKG_TEST;
/