CREATE OR REPLACE PACKAGE temperature_converter_pkg_test IS
--%suite(Temperature Converter Package Tests)
--%suitepath(Temperature_Converter)

  --%test(Celsius to Kelvin conversion)
  PROCEDURE test_celsius_to_kelvin;

  --%test(Celsius to Kelvin below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE test_celsius_to_kelvin_negative;

  --%test(Kelvin to Celsius conversion)
  PROCEDURE test_kelvin_to_celsius;

  --%test(Kelvin to Celsius below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE test_kelvin_to_celsius_negative;

  --%test(Celsius to Fahrenheit conversion)
  PROCEDURE test_celsius_to_fahrenheit;

  --%test(Celsius to Fahrenheit below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE test_celsius_to_fahrenheit_negative;

  --%test(Fahrenheit to Celsius conversion)
  PROCEDURE test_fahrenheit_to_celsius;

  --%test(Fahrenheit to Celsius below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE test_fahrenheit_to_celsius_negative;

  --%test(Kelvin to Fahrenheit conversion)
  PROCEDURE test_kelvin_to_fahrenheit;

  --%test(Kelvin to Fahrenheit below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE test_kelvin_to_fahrenheit_negative;

  --%test(Fahrenheit to Kelvin conversion)
  PROCEDURE test_fahrenheit_to_kelvin;

  --%test(Fahrenheit to Kelvin below absolute zero - should raise exception)
  --%throws(temperature_converter_pkg.absolute_zero)
  PROCEDURE test_fahrenheit_to_kelvin_negative;

END temperature_converter_pkg_test;
/

CREATE OR REPLACE PACKAGE BODY DISTANCE_CONVERTER_PKG_TEST IS

  PROCEDURE TEST_METERS_TO_YARDS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_YARDS(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(1.0936, 1.0937);
  END TEST_METERS_TO_YARDS;

  PROCEDURE TEST_METERS_TO_YARDS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_YARDS(-1);
  /*EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001);*/
  END TEST_METERS_TO_YARDS_NEGATIVE;

  PROCEDURE TEST_YARDS_TO_METERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.YARDS_TO_METERS(1.0936133);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(0.9999, 1.0001);
  END TEST_YARDS_TO_METERS;

  PROCEDURE TEST_YARDS_TO_METERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.YARDS_TO_METERS(-1);
  /*EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001);*/
  END TEST_YARDS_TO_METERS_NEGATIVE;

  PROCEDURE TEST_METERS_TO_FEET IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_FEET(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(3.2808, 3.2809);
  END TEST_METERS_TO_FEET;

  PROCEDURE TEST_METERS_TO_FEET_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_FEET(-1);
  /*EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001);*/
  END TEST_METERS_TO_FEET_NEGATIVE;

  PROCEDURE TEST_FEET_TO_METERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.FEET_TO_METERS(3.2808399);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(0.9999, 1.0001);
  END TEST_FEET_TO_METERS;

  PROCEDURE TEST_FEET_TO_METERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.FEET_TO_METERS(-1);
  /*EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001);*/
  END TEST_FEET_TO_METERS_NEGATIVE;

  PROCEDURE TEST_METERS_TO_INCHES IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_INCHES(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(39.3700, 39.3701);
  END TEST_METERS_TO_INCHES;

  PROCEDURE TEST_METERS_TO_INCHES_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.METERS_TO_INCHES(-1);
  /*EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001);*/
  END TEST_METERS_TO_INCHES_NEGATIVE;

  PROCEDURE TEST_INCHES_TO_METERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.INCHES_TO_METERS(39.3700787);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(0.9999, 1.0001);
  END TEST_INCHES_TO_METERS;

  PROCEDURE TEST_INCHES_TO_METERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.INCHES_TO_METERS(-1);
  /*EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001);*/
  END TEST_INCHES_TO_METERS_NEGATIVE;

  PROCEDURE TEST_KILOMETERS_TO_MILES IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.KILOMETERS_TO_MILES(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(0.6213, 0.6214);
  END TEST_KILOMETERS_TO_MILES;

  PROCEDURE TEST_KILOMETERS_TO_MILES_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.KILOMETERS_TO_MILES(-1);
  /*EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001);*/
  END TEST_KILOMETERS_TO_MILES_NEGATIVE;

  PROCEDURE TEST_MILES_TO_KILOMETERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.MILES_TO_KILOMETERS(0.621371192);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(0.9999, 1.0001);
  END TEST_MILES_TO_KILOMETERS;

  PROCEDURE TEST_MILES_TO_KILOMETERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := DISTANCE_CONVERTER_PKG.MILES_TO_KILOMETERS(-1);
  /*EXCEPTION
    WHEN DISTANCE_CONVERTER_PKG.DISTANCE_NEGATIVE THEN
      UT.EXPECT(SQLCODE).TO_EQUAL(-20001);*/
  END TEST_MILES_TO_KILOMETERS_NEGATIVE;

END DISTANCE_CONVERTER_PKG_TEST;
/