CREATE OR REPLACE PACKAGE VOLUME_CONVERTER_PKG_TEST IS
--%suite(Volume Converter Package Tests)
--%suitepath(Volume_Converter)

  --%test(Liters to Gallons conversion)
  PROCEDURE TEST_LITERS_TO_GALLONS;

  --%test(Liters to Gallons negative volume)
  --%throws(volume_converter_pkg.volume_negative)
  PROCEDURE TEST_LITERS_TO_GALLONS_NEGATIVE;

  --%test(Gallons to Liters conversion)
  PROCEDURE TEST_GALLONS_TO_LITERS;

  --%test(Gallons to Liters negative volume)
  --%throws(volume_converter_pkg.volume_negative)
  PROCEDURE TEST_GALLONS_TO_LITERS_NEGATIVE;

  --%test(Liters to Pints conversion)
  PROCEDURE TEST_LITERS_TO_PINTS;

  --%test(Liters to Pints negative volume)
  --%throws(volume_converter_pkg.volume_negative)
  PROCEDURE TEST_LITERS_TO_PINTS_NEGATIVE;

  --%test(Pints to Liters conversion)
  PROCEDURE TEST_PINTS_TO_LITERS;

  --%test(Pints to Liters negative volume)
  --%throws(volume_converter_pkg.volume_negative)
  PROCEDURE TEST_PINTS_TO_LITERS_NEGATIVE;

  --%test(Liters to Fluid Ounces conversion)
  PROCEDURE TEST_LITERS_TO_FLUID_OUNCES;

  --%test(Liters to Fluid Ounces negative volume)
  --%throws(volume_converter_pkg.volume_negative)
  PROCEDURE TEST_LITERS_TO_FLUID_OUNCES_NEGATIVE;

  --%test(Fluid Ounces to Liters conversion)
  PROCEDURE TEST_FLUID_OUNCES_TO_LITERS;

  --%test(Fluid Ounces to Liters negative volume)
  --%throws(volume_converter_pkg.volume_negative)
  PROCEDURE TEST_FLUID_OUNCES_TO_LITERS_NEGATIVE;

  --%test(Cubic Meters to Cubic Feet conversion)
  PROCEDURE TEST_CUBIC_METERS_TO_CUBIC_FEET;

  --%test(Cubic Meters to Cubic Feet negative volume)
  --%throws(volume_converter_pkg.volume_negative)
  PROCEDURE TEST_CUBIC_METERS_TO_CUBIC_FEET_NEGATIVE;

  --%test(Cubic Feet to Cubic Meters conversion)
  PROCEDURE TEST_CUBIC_FEET_TO_CUBIC_METERS;

  --%test(Cubic Feet to Cubic Meters negative volume)
  --%throws(volume_converter_pkg.volume_negative)
  PROCEDURE TEST_CUBIC_FEET_TO_CUBIC_METERS_NEGATIVE;

END VOLUME_CONVERTER_PKG_TEST;
/

CREATE OR REPLACE PACKAGE BODY VOLUME_CONVERTER_PKG_TEST IS

  PROCEDURE TEST_LITERS_TO_GALLONS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.LITERS_TO_GALLONS(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.26417
     ,0.26418
    );
  END TEST_LITERS_TO_GALLONS;

  PROCEDURE TEST_LITERS_TO_GALLONS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.LITERS_TO_GALLONS(-1);
  /*EXCEPTION
    WHEN volume_converter_pkg.volume_negative THEN
      ut.expect(sqlcode).to_equal(-20003);*/
  END TEST_LITERS_TO_GALLONS_NEGATIVE;

  PROCEDURE TEST_GALLONS_TO_LITERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.GALLONS_TO_LITERS(0.264172052);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.9999
     ,1.0001
    );
  END TEST_GALLONS_TO_LITERS;

  PROCEDURE TEST_GALLONS_TO_LITERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.GALLONS_TO_LITERS(-1);
  /*EXCEPTION
    WHEN volume_converter_pkg.volume_negative THEN
      ut.expect(sqlcode).to_equal(-20003);*/
  END TEST_GALLONS_TO_LITERS_NEGATIVE;

  PROCEDURE TEST_LITERS_TO_PINTS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.LITERS_TO_PINTS(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      2.1133
     ,2.1135
    );
  END TEST_LITERS_TO_PINTS;

  PROCEDURE TEST_LITERS_TO_PINTS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.LITERS_TO_PINTS(-1);
  /*EXCEPTION
    WHEN volume_converter_pkg.volume_negative THEN
      ut.expect(sqlcode).to_equal(-20003);*/
  END TEST_LITERS_TO_PINTS_NEGATIVE;

  PROCEDURE TEST_PINTS_TO_LITERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.PINTS_TO_LITERS(2.11337642);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.9999
     ,1.0001
    );
  END TEST_PINTS_TO_LITERS;

  PROCEDURE TEST_PINTS_TO_LITERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.PINTS_TO_LITERS(-1);
  /*EXCEPTION
    WHEN volume_converter_pkg.volume_negative THEN
      ut.expect(sqlcode).to_equal(-20003);*/
  END TEST_PINTS_TO_LITERS_NEGATIVE;

  PROCEDURE TEST_LITERS_TO_FLUID_OUNCES IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.LITERS_TO_FLUID_OUNCES(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      33.8140
     ,33.8141
    );
  END TEST_LITERS_TO_FLUID_OUNCES;

  PROCEDURE TEST_LITERS_TO_FLUID_OUNCES_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.LITERS_TO_FLUID_OUNCES(-1);
  /*EXCEPTION
    WHEN volume_converter_pkg.volume_negative THEN
      ut.expect(sqlcode).to_equal(-20003);*/
  END TEST_LITERS_TO_FLUID_OUNCES_NEGATIVE;

  PROCEDURE TEST_FLUID_OUNCES_TO_LITERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.FLUID_OUNCES_TO_LITERS(33.8140227);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.9999
     ,1.0001
    );
  END TEST_FLUID_OUNCES_TO_LITERS;

  PROCEDURE TEST_FLUID_OUNCES_TO_LITERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.FLUID_OUNCES_TO_LITERS(-1);
  /*EXCEPTION
    WHEN volume_converter_pkg.volume_negative THEN
      ut.expect(sqlcode).to_equal(-20003);*/
  END TEST_FLUID_OUNCES_TO_LITERS_NEGATIVE;

  PROCEDURE TEST_CUBIC_METERS_TO_CUBIC_FEET IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.CUBIC_METERS_TO_CUBIC_FEET(1);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      35.3146
     ,35.3147
    );
  END TEST_CUBIC_METERS_TO_CUBIC_FEET;

  PROCEDURE TEST_CUBIC_METERS_TO_CUBIC_FEET_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.CUBIC_METERS_TO_CUBIC_FEET(-1);
  /*EXCEPTION
    WHEN volume_converter_pkg.volume_negative THEN
      ut.expect(sqlcode).to_equal(-20003);*/
  END TEST_CUBIC_METERS_TO_CUBIC_FEET_NEGATIVE;

  PROCEDURE TEST_CUBIC_FEET_TO_CUBIC_METERS IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.CUBIC_FEET_TO_CUBIC_METERS(35.3146667);
    UT.EXPECT(L_RESULT).TO_BE_BETWEEN(
      0.9999
     ,1.0001
    );
  END TEST_CUBIC_FEET_TO_CUBIC_METERS;

  PROCEDURE TEST_CUBIC_FEET_TO_CUBIC_METERS_NEGATIVE IS
    L_RESULT NUMBER;
  BEGIN
    L_RESULT := VOLUME_CONVERTER_PKG.CUBIC_FEET_TO_CUBIC_METERS(-1);
  /*EXCEPTION
    WHEN volume_converter_pkg.volume_negative THEN
      ut.expect(sqlcode).to_equal(-20003);*/
  END TEST_CUBIC_FEET_TO_CUBIC_METERS_NEGATIVE;

END VOLUME_CONVERTER_PKG_TEST;
/