name: Run utPLSQL Tests
#run-name: ${{ github.actor }} TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      oracle:
        image: gvenzl/oracle-xe
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: oracle
        options: >-
          --health-cmd "echo 'select 1 from dual;' | sqlplus -s system/oracle@//localhost/XEPDB1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Install SQLcl
        run: |
          curl -L -o sqlcl.zip https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-25.2.1.195.1751.zip
          unzip sqlcl.zip -d sqlcl

      - name: Download and install utPLSQL
        run: |
          git clone https://github.com/utPLSQL/utPLSQL.git
          ./sqlcl/sqlcl/bin/sql -S sys/oracle@//localhost/XEPDB1 as sysdba @utPLSQL/source/install_headless.sql
          ./sqlcl/sqlcl/bin/sql -S sys/oracle@//localhost/XEPDB1 as sysdba @ut3_grants.sql
           
      - name: Run Tests
        run: |
          ./sqlcl/sqlcl/bin/sql -S sys/oracle@//localhost/XEPDB1 as sysdba @code/install_calculator.sql
          ./sqlcl/sqlcl/bin/sql -S sys/oracle@//localhost/XEPDB1 as sysdba @tests/install_tests.sql
          ./sqlcl/sqlcl/bin/sql -S sys/oracle@//localhost/XEPDB1 as sysdba @run_tests.sql
          
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: utplsql-test-results
          path: ut_results.xml

      - name: Publish test summary to GitHub UI
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: ut_results.xml
          check_name: 'PL/SQL Unit Tests'
          include_passed: true
          fail_on_failure: true
          detailed_summary: true
          summary: |
            <details>
            <summary>Test Results</summary>
            <pre>
            $(cat ut_results.xml)
            </pre>
            </details>

      - name: Search for errors
        run: |
          bash analyze_test_output.sh

